meta_product_name: "crowdAI"
meta_title: "crowdAI"
meta_description: "Fighting for Open Science with Open Data"
meta_image: "misc/crowdai-head.png"                      
twitter_account: "@crowd_ai"   # required for Twitter Cards
